name: CI / CD

on:
  push:
    branches: [master]
  pull_request:
  release:
    types: [published]

env: 
  NODE_VERSION: 14.x

jobs:
  test:
    name: Test
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: install
        run: npm i

      - name: test-unit
        run: npm run test

     - name: lint
       run: npm run lint

  build:
    name: Build
    runs-on: [self-hosted, linux]
    needs: [test]
    steps: 
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: install
        run: npm i

      - name: build
        run: npm run build
