name: CI / CD

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

env: 
    NODE_VERSION: 14.x

jobs:
    test:
        name: Test
        runs-on: self-hosted
        steps:
            - name: checkout master
              uses: actions/checkout@v2

            - name: setup node.js
              uses: actions/setup-node@v1
              with:
                node-version: ${{ env.NODE_VERSION }}

            - name: install
              run: yarn install

            - name: test-unit
              run: yarn test

            - name: lint
              run: yarn lint

    build:
        name: Build
        runs-on: self-hosted
        needs: [test]
        steps: 
            - name: checkout master
              uses: actions/checkout@v2

            - name: setup node.js
              uses: actions/setup-node@v1
              with:
                node-version: ${{ env.NODE_VERSION }}

            - name: install
              run: yarn install

            - name: build
              run: yarn build
