name: CD

on:
    pull_request:
        types: [ closed ]

env: 
    NODE_VERSION: 14.x

jobs:
    build:
        name: Build
        runs-on: self-hosted
        needs: [test]
        steps: 
            - name: checkout master
              uses: actions/checkout@v2

            - name: setup node.js and npm
              uses: actions/setup-node@v2
              with:
                node-version: ${{ env.NODE_VERSION }}

            - name: install
              run: npm i

            - name: build
              run: npm run build
