name: CI / CD

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]
        types: [opened, closed]

env: 
    NODE_VERSION: 14.x
    PR_MERGE_VALIDATION: github.event.pull_request.merged

jobs:
    test:
        name: Test
        runs-on: self-hosted
        steps:
            - name: checkout master
              uses: actions/checkout@v2

            - name: setup node.js and npm
              uses: actions/setup-node@v2
              with:
                node-version: ${{ env.NODE_VERSION }}

            - name: install
              run: npm i

            - name: test unit
              run: npm run test

            - name: check coverage
              run: npm run test:coverage

            - name: lint
              run: npm run lint

    build:
        if: ${{ env.PR_MERGE_VALIDATION }}
        name: Build
        runs-on: self-hosted
        needs: [test]
        steps: 
            - name: checkout master
              uses: actions/checkout@v2

            - name: setup node.js and npm
              uses: actions/setup-node@v2
              with:
                node-version: ${{ env.NODE_VERSION }}

            - name: install
              run: npm i

            - name: build
              run: npm run build
